"""Добавил в модель в столбце query убрад unique

Revision ID: 1aa25e4dcfdc
Revises: 6372a6bff539
Create Date: 2026-07-01 21:02:48.836085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa25e4dcfdc'
down_revision: Union[str, Sequence[str], None] = '6372a6bff539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('history_query_key'), 'history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('history_query_key'), 'history', ['query'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
