"""Добавил в модель в query свойство уникальности

Revision ID: 50ea61ad39ec
Revises: 7321eda1c59d
Create Date: 2026-07-01 16:58:38.152445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ea61ad39ec'
down_revision: Union[str, Sequence[str], None] = '7321eda1c59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'history', ['query'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='unique')
    # ### end Alembic commands ###
