"""Добавил в модель history поле is_watched

Revision ID: 7321eda1c59d
Revises: df85a179f7bd
Create Date: 2026-07-01 16:50:19.692891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7321eda1c59d'
down_revision: Union[str, Sequence[str], None] = 'df85a179f7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('is_watched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'is_watched')
    # ### end Alembic commands ###
