"""Добавил таблицу history

Revision ID: df85a179f7bd
Revises: 
Create Date: 2026-07-01 14:05:08.748131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df85a179f7bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_vk_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('command', sa.VARCHAR(length=50), nullable=False),
    sa.Column('query', sa.VARCHAR(length=200), nullable=False),
    sa.Column('result_preview', sa.Text(), nullable=False),
    sa.Column('next_page_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('prev_page_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
